version: '3.7'

services:
  cache:
    image: redis
    container_name: telegram_rent_cache
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - telegram_rent

  db:
    image: postgres:13
    container_name: telegram_rent_db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_DATABASE:-telegram_rent}'
      POSTGRES_USER: '${DB_USERNAME:-telegram_rent}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-telegram_rent}'
    ports:
      - '${FORWARD_DB_PORT:-25432}:5432'
    networks:
      - telegram_rent

  php:
    build:
      context: ./docker/local/php/
      dockerfile: Dockerfile
    image: telegram_rent_php:dev
    container_name: telegram_rent_php
    volumes:
      - ./php-backend:/app
    networks:
      - telegram_rent
    depends_on:
      - cache
      - db
    healthcheck:
      test: [ "CMD-SHELL", "php artisan healthcheck:run || exit 1" ]
      interval: 5m
      timeout: 3s

  nginx:
    image: nginx:alpine
    container_name: telegram_rent_nginx
    working_dir: /app
    volumes:
      - ./media:/app/public/media
      - ./php-backend:/app
      - ./docker/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${APP_PORT:-7100}:80'
    depends_on:
      - php
    networks:
      - telegram_rent

  node:
    build:
      context: ./docker/local/node/
      dockerfile: Dockerfile
    image: telegram_rent_node:dev
    container_name: telegram_rent_node
    volumes:
      - ./node-frontend:/nuxt-app
    networks:
      - telegram_rent
    depends_on:
      - php

  python:
    build:
      context: ./docker/local/python/
      dockerfile: Dockerfile
    init: true
    image: telegram_rent_python:dev
    container_name: telegram_rent_python
    volumes:
      - ./media:/media
      - ./python-parser:/app
    networks:
      - telegram_rent
    depends_on:
      - cache
      - db
    # healthcheck:
    #   test: [ "CMD-SHELL", "php artisan healthcheck:run || exit 1" ]
    #   interval: 5m
    #   timeout: 3s

networks:
  telegram_rent:
    driver: bridge

volumes:
  media:
  database:
    driver: local
